name: Fetch EMPARN Twice Daily

on:
  schedule:
    # BRT 09:15 e 18:15  -> UTC 12:15 e 21:15
    - cron: '15 12 * * *'
    - cron: '15 21 * * *'
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm init -y
          npm i playwright papaparse

      - name: Run scraper (Chromium headless)
        run: node scripts/fetch-emparn-playwright.cjs

      - name: Versionar com timestamp (UTC-3) e manter latest.*
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data
          TSTAMP=$(TZ=America/Fortaleza date +'%Y-%m-%d_%H%M')
          for ext in csv txt json; do
            if [ -s "data/latest.$ext" ]; then
              cp "data/latest.$ext" "data/${TSTAMP}.$ext"
            fi
          done
          ls -lh data | sed -n '1,200p'

      - name: Commit files
        run: |