name: Fetch EMPARN Daily

on:
  schedule:
    - cron: '15 12 * * *'    # 09:15 BRT (UTC-3)
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm init -y
          npm i playwright

      - name: Run scraper (Chromium headless)
        run: node scripts/fetch-emparn-playwright.cjs

      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: emparn-rendered
          path: |
            data/rendered.html
            data/links.txt

      - name: Commit files
        run: |
          git config user.name "pluvio-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data/latest.csv data/latest.txt || true
          git commit -m "chore: daily EMPARN snapshot" || echo "no changes"
          git push || true