# .github/workflows/fetch-emparn.yml
name: Fetch EMPARN Twice Daily

on:
  schedule:
    - cron: '15 12 * * *'   # 09:15 BRT
    - cron: '15 21 * * *'   # 18:15 BRT
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Playwright + PapaParse
        run: |
          npm init -y
          npm i playwright papaparse
      - name: Run scraper
        run: node scripts/fetch-emparn-playwright.cjs
      - name: Timestamp snapshot (UTC-3) + keep latest.*
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data
          TSTAMP=$(TZ=America/Fortaleza date +'%Y-%m-%d_%H%M')
          for ext in csv txt json; do
            if [ -s "data/latest.$ext" ]; then
              cp "data/latest.$ext" "data/${TSTAMP}.$ext"
            fi
          done
      - name: Commit
        run: |
          git config user.name "pluvio-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data/latest.* data/*.csv data/*.txt data/*.json || true
          git commit -m "EMPARN snapshot (twice daily)" || echo "no changes"
          git push || true
