name: Fetch EMPARN Twice Daily

on:
  schedule:
    # Horários em UTC (equivalem a 09:15 e 18:15 em America/Fortaleza / UTC-3)
    - cron: '15 12 * * *'
    - cron: '15 21 * * *'
  workflow_dispatch: {}  # permite rodar manualmente

permissions:
  contents: write  # necessário para commit/push

concurrency:
  group: emparn-fetch
  cancel-in-progress: true

env:
  TZ: America/Fortaleza

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright + PapaParse (with Chromium)
        run: |
          npm init -y
          npm i playwright papaparse
          npx playwright install --with-deps chromium

      - name: (debug) List repo tree
        run: |
          pwd
          ls -lah
          ls -lah scripts || true

      - name: Run scraper
        run: node scripts/fetch-emparn-playwright.js

      - name: Timestamp snapshot (UTC-3) and keep latest.*
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data
          TSTAMP=$(date +'%Y-%m-%d_%H%M')
          for ext in csv txt json; do
            if [ -s "data/latest.$ext" ]; then
              cp "data/latest.$ext" "data/${TSTAMP}.$ext"
            fi
          done
          ls -lh data | sed -n '1,200p'

      - name: Commit & Push
        run: |
          git config user.name "pluvio-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data/latest.* data/*.csv data/*.txt data/*.json || true
          git commit -m "EMPARN snapshot (twice daily)" || echo "no changes"
          git push || true

      - name: Upload debug artifacts (rendered HTML if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: emparn-debug
          path: |
            data/rendered.html
          if-no-files-found: ignore
