name: Fetch EMPARN Daily

on:
  schedule:
    # 09:15 BRT = 12:15 UTC
    - cron: '15 12 * * *'
  workflow_dispatch: {}   # permite rodar manualmente

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm i node-fetch@3 cheerio@1

      - name: Fetch CSV/TXT from EMPARN
        run: node scripts/fetch-emparn.js

      - name: Commit files
        run: |
          git config user.name "pluvio-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data/latest.csv data/latest.txt || true
          git commit -m "chore: daily EMPARN snapshot" || echo "no changes"
          git push || true
