name: Fetch EMPARN Twice Daily

on:
  schedule:
    # Horário de Brasília (UTC-3) ≈ 09:15 e 18:15  -> em UTC: 12:15 e 21:15
    - cron: '15 12 * * *'
    - cron: '15 21 * * *'
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm init -y
          npm i playwright

      - name: Run scraper (Chromium headless)
        run: node scripts/fetch-emparn-playwright.cjs

      - name: Versionar com timestamp (UTC-3) e manter latest.*
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data
          # carimbo em America/Fortaleza (UTC-3)
          TSTAMP=$(TZ=America/Fortaleza date +'%Y-%m-%d_%H%M')
          if [ -s data/latest.csv ]; then
            cp data/latest.csv "data/${TSTAMP}.csv"
          elif [ -s data/latest.txt ]; then
            cp data/latest.txt "data/${TSTAMP}.txt"
          fi
          ls -lh data | sed -n '1,120p'

      - name: Commit files
        run: |
          git config user.name "pluvio-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data/latest.csv data/latest.txt data/*.csv data/*.txt || true
          git commit -m "chore: EMPARN snapshot (twice daily)" || echo "no changes"
          git push || true